// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aifedorov/goavatar/internal/domain (interfaces: AvatarRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . AvatarRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/aifedorov/goavatar/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAvatarRepository) Create(ctx context.Context, avatar *domain.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAvatarRepositoryMockRecorder) Create(ctx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAvatarRepository)(nil).Create), ctx, avatar)
}

// GetByID mocks base method.
func (m *MockAvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockAvatarRepository) GetByUserID(ctx context.Context, userID string) ([]*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockAvatarRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).GetByUserID), ctx, userID)
}

// GetLatestByUserID mocks base method.
func (m *MockAvatarRepository) GetLatestByUserID(ctx context.Context, userID string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUserID indicates an expected call of GetLatestByUserID.
func (mr *MockAvatarRepositoryMockRecorder) GetLatestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).GetLatestByUserID), ctx, userID)
}

// GetProcessingStatus mocks base method.
func (m *MockAvatarRepository) GetProcessingStatus(ctx context.Context, id uuid.UUID) (domain.ProcessingStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessingStatus", ctx, id)
	ret0, _ := ret[0].(domain.ProcessingStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessingStatus indicates an expected call of GetProcessingStatus.
func (mr *MockAvatarRepositoryMockRecorder) GetProcessingStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessingStatus", reflect.TypeOf((*MockAvatarRepository)(nil).GetProcessingStatus), ctx, id)
}

// SetUploadFailed mocks base method.
func (m *MockAvatarRepository) SetUploadFailed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUploadFailed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUploadFailed indicates an expected call of SetUploadFailed.
func (mr *MockAvatarRepositoryMockRecorder) SetUploadFailed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUploadFailed", reflect.TypeOf((*MockAvatarRepository)(nil).SetUploadFailed), ctx, id)
}

// SetUploaded mocks base method.
func (m *MockAvatarRepository) SetUploaded(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUploaded", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUploaded indicates an expected call of SetUploaded.
func (mr *MockAvatarRepositoryMockRecorder) SetUploaded(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUploaded", reflect.TypeOf((*MockAvatarRepository)(nil).SetUploaded), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockAvatarRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAvatarRepositoryMockRecorder) SoftDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAvatarRepository)(nil).SoftDelete), ctx, id, userID)
}

// TotalStorageBytes mocks base method.
func (m *MockAvatarRepository) TotalStorageBytes(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalStorageBytes", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalStorageBytes indicates an expected call of TotalStorageBytes.
func (mr *MockAvatarRepositoryMockRecorder) TotalStorageBytes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalStorageBytes", reflect.TypeOf((*MockAvatarRepository)(nil).TotalStorageBytes), ctx)
}

// UpdateProcessingStatus mocks base method.
func (m *MockAvatarRepository) UpdateProcessingStatus(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus, thumbnails map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", ctx, id, status, thumbnails)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockAvatarRepositoryMockRecorder) UpdateProcessingStatus(ctx, id, status, thumbnails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateProcessingStatus), ctx, id, status, thumbnails)
}
