// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aifedorov/goavatar/internal/domain (interfaces: AvatarEventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_publisher.go -package=mocks . AvatarEventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/aifedorov/goavatar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarEventPublisher is a mock of AvatarEventPublisher interface.
type MockAvatarEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarEventPublisherMockRecorder
	isgomock struct{}
}

// MockAvatarEventPublisherMockRecorder is the mock recorder for MockAvatarEventPublisher.
type MockAvatarEventPublisherMockRecorder struct {
	mock *MockAvatarEventPublisher
}

// NewMockAvatarEventPublisher creates a new mock instance.
func NewMockAvatarEventPublisher(ctrl *gomock.Controller) *MockAvatarEventPublisher {
	mock := &MockAvatarEventPublisher{ctrl: ctrl}
	mock.recorder = &MockAvatarEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarEventPublisher) EXPECT() *MockAvatarEventPublisherMockRecorder {
	return m.recorder
}

// PublishDeleteEvent mocks base method.
func (m *MockAvatarEventPublisher) PublishDeleteEvent(ctx context.Context, event domain.AvatarDeleteEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeleteEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDeleteEvent indicates an expected call of PublishDeleteEvent.
func (mr *MockAvatarEventPublisherMockRecorder) PublishDeleteEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeleteEvent", reflect.TypeOf((*MockAvatarEventPublisher)(nil).PublishDeleteEvent), ctx, event)
}

// PublishUploadEvent mocks base method.
func (m *MockAvatarEventPublisher) PublishUploadEvent(ctx context.Context, event domain.AvatarUploadEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUploadEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUploadEvent indicates an expected call of PublishUploadEvent.
func (mr *MockAvatarEventPublisherMockRecorder) PublishUploadEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUploadEvent", reflect.TypeOf((*MockAvatarEventPublisher)(nil).PublishUploadEvent), ctx, event)
}
