// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvatarMetadataMimeType.
const (
	Imagejpeg AvatarMetadataMimeType = "image/jpeg"
	Imagepng  AvatarMetadataMimeType = "image/png"
	Imagewebp AvatarMetadataMimeType = "image/webp"
)

// Defines values for ComponentStatusStatus.
const (
	ComponentStatusStatusDown ComponentStatusStatus = "down"
	ComponentStatusStatusOk   ComponentStatusStatus = "ok"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Defines values for ProcessingStatus.
const (
	Completed  ProcessingStatus = "completed"
	Failed     ProcessingStatus = "failed"
	Pending    ProcessingStatus = "pending"
	Processing ProcessingStatus = "processing"
)

// AvatarListItem defines model for AvatarListItem.
type AvatarListItem struct {
	CreatedAt time.Time          `json:"created_at"`
	FileName  string             `json:"file_name"`
	Id        openapi_types.UUID `json:"id"`
	Status    ProcessingStatus   `json:"status"`
	Url       string             `json:"url"`
	UserId    string             `json:"user_id"`
}

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time              `json:"created_at"`
	FileName   string                 `json:"file_name"`
	Id         openapi_types.UUID     `json:"id"`
	MimeType   AvatarMetadataMimeType `json:"mime_type"`
	Size       int64                  `json:"size"`
	Thumbnails []Thumbnail            `json:"thumbnails"`
	UpdatedAt  time.Time              `json:"updated_at"`
	UserId     string                 `json:"user_id"`
}

// AvatarMetadataMimeType defines model for AvatarMetadata.MimeType.
type AvatarMetadataMimeType string

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	Error  *string               `json:"error,omitempty"`
	Name   string                `json:"name"`
	Status ComponentStatusStatus `json:"status"`
}

// ComponentStatusStatus defines model for ComponentStatus.Status.
type ComponentStatusStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// FileTooLargeResponse defines model for FileTooLargeResponse.
type FileTooLargeResponse struct {
	Error   string `json:"error"`
	MaxSize int64  `json:"max_size"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Components []ComponentStatus    `json:"components"`
	Status     HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ProcessingStatus defines model for ProcessingStatus.
type ProcessingStatus string

// Thumbnail defines model for Thumbnail.
type Thumbnail struct {
	Size string `json:"size"`
	Url  string `json:"url"`
}

// UploadAvatarResponse defines model for UploadAvatarResponse.
type UploadAvatarResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Status    ProcessingStatus   `json:"status"`
	Url       string             `json:"url"`
	UserId    string             `json:"user_id"`
}

// AvatarIDPath defines model for AvatarIDPath.
type AvatarIDPath = openapi_types.UUID

// ImageSizeQuery defines model for ImageSizeQuery.
type ImageSizeQuery = string

// UserIDHeader defines model for UserIDHeader.
type UserIDHeader = string

// UserIDPath defines model for UserIDPath.
type UserIDPath = string

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	// XUserID Authenticated user identifier.
	XUserID UserIDHeader `json:"X-User-ID"`
}

// DeleteAvatarParams defines parameters for DeleteAvatar.
type DeleteAvatarParams struct {
	// XUserID Authenticated user identifier.
	XUserID UserIDHeader `json:"X-User-ID"`
}

// GetAvatarImageParams defines parameters for GetAvatarImage.
type GetAvatarImageParams struct {
	// Size Optional thumbnail size.
	Size *ImageSizeQuery `form:"size,omitempty" json:"size,omitempty"`
}

// DeleteUserAvatarParams defines parameters for DeleteUserAvatar.
type DeleteUserAvatarParams struct {
	// XUserID Authenticated user identifier.
	XUserID UserIDHeader `json:"X-User-ID"`
}

// GetUserAvatarImageParams defines parameters for GetUserAvatarImage.
type GetUserAvatarImageParams struct {
	// Size Optional thumbnail size.
	Size *ImageSizeQuery `form:"size,omitempty" json:"size,omitempty"`
}

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody
