apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: {{ include "goavatar.namespace" . }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
