apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ include "goavatar.namespace" . }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ required "postgres.password is required" .Values.postgres.password | quote }}
