apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: {{ include "goavatar.namespace" . }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ required "rabbitmq.username is required" .Values.rabbitmq.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ required "rabbitmq.password is required" .Values.rabbitmq.password | quote }}
