apiVersion: v1
kind: Secret
metadata:
  name: goavatar-secrets
  namespace: {{ include "goavatar.namespace" . }}
type: Opaque
stringData:
  DATABASE_URI: {{ .Values.secrets.databaseUri | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  RABBITMQ_URL: {{ .Values.secrets.rabbitmqUrl | quote }}
