// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: avatars.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvatar = `-- name: CreateAvatar :one
INSERT INTO avatars (id, user_id, file_name, mime_type, size_bytes, s3_key, upload_status, processing_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, file_name, mime_type, size_bytes, s3_key, thumbnail_s3_keys, upload_status, processing_status, created_at, updated_at, deleted_at
`

type CreateAvatarParams struct {
	ID               pgtype.UUID
	UserID           string
	FileName         string
	MimeType         string
	SizeBytes        int64
	S3Key            string
	UploadStatus     string
	ProcessingStatus string
}

func (q *Queries) CreateAvatar(ctx context.Context, arg CreateAvatarParams) (Avatar, error) {
	row := q.db.QueryRow(ctx, createAvatar,
		arg.ID,
		arg.UserID,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.S3Key,
		arg.UploadStatus,
		arg.ProcessingStatus,
	)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.S3Key,
		&i.ThumbnailS3Keys,
		&i.UploadStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
