// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessingStatus string

const (
	ProcessingStatusPending    ProcessingStatus = "pending"
	ProcessingStatusProcessing ProcessingStatus = "processing"
	ProcessingStatusCompleted  ProcessingStatus = "completed"
	ProcessingStatusFailed     ProcessingStatus = "failed"
)

func (e *ProcessingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingStatus(s)
	case string:
		*e = ProcessingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingStatus: %T", src)
	}
	return nil
}

type NullProcessingStatus struct {
	ProcessingStatus ProcessingStatus
	Valid            bool // Valid is true if ProcessingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingStatus), nil
}

type UploadStatus string

const (
	UploadStatusUploading UploadStatus = "uploading"
	UploadStatusUploaded  UploadStatus = "uploaded"
	UploadStatusFailed    UploadStatus = "failed"
)

func (e *UploadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadStatus(s)
	case string:
		*e = UploadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadStatus: %T", src)
	}
	return nil
}

type NullUploadStatus struct {
	UploadStatus UploadStatus
	Valid        bool // Valid is true if UploadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadStatus), nil
}

type Avatar struct {
	ID               pgtype.UUID
	UserID           string
	FileName         string
	MimeType         string
	SizeBytes        int64
	S3Key            string
	ThumbnailS3Keys  []byte
	UploadStatus     UploadStatus
	ProcessingStatus ProcessingStatus
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}
