receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  rabbitmq:
    endpoint: http://rabbitmq:15672
    username: rabbitmq
    password: rabbitmq
    collection_interval: 15s

  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: goavatar
    password: password
    databases:
      - goavatar
    tls:
      insecure: true
    collection_interval: 15s

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true

  opensearch:
    http:
      endpoint: http://opensearch:9200
    logs_index: otel-logs

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/jaeger ]
    metrics:
      receivers: [ otlp, rabbitmq, postgresql ]
      processors: [ memory_limiter, batch ]
      exporters: [ prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ opensearch ]

  telemetry:
    logs:
      level: info
