apiVersion: batch/v1
kind: Job
metadata:
  name: goavatar-migrate
  namespace: goavatar
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: migrate/migrate:v4.18.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: goavatar-secrets
                  key: DATABASE_URI
          args:
            - -path
            - /migrations
            - -database
            - $(DATABASE_URI)
            - up
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: goavatar-migrations
