// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aifedorov/goavatar/internal/handlers (interfaces: AvatarGetter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_avatar_getter.go -package=mocks . AvatarGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/aifedorov/goavatar/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarGetter is a mock of AvatarGetter interface.
type MockAvatarGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarGetterMockRecorder
	isgomock struct{}
}

// MockAvatarGetterMockRecorder is the mock recorder for MockAvatarGetter.
type MockAvatarGetterMockRecorder struct {
	mock *MockAvatarGetter
}

// NewMockAvatarGetter creates a new mock instance.
func NewMockAvatarGetter(ctrl *gomock.Controller) *MockAvatarGetter {
	mock := &MockAvatarGetter{ctrl: ctrl}
	mock.recorder = &MockAvatarGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarGetter) EXPECT() *MockAvatarGetterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAvatarGetter) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarGetterMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarGetter)(nil).GetByID), ctx, id)
}

// GetImage mocks base method.
func (m *MockAvatarGetter) GetImage(ctx context.Context, id uuid.UUID, size string) (*domain.Avatar, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id, size)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetImage indicates an expected call of GetImage.
func (mr *MockAvatarGetterMockRecorder) GetImage(ctx, id, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockAvatarGetter)(nil).GetImage), ctx, id, size)
}

// GetUserImage mocks base method.
func (m *MockAvatarGetter) GetUserImage(ctx context.Context, userID, size string) (*domain.Avatar, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserImage", ctx, userID, size)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserImage indicates an expected call of GetUserImage.
func (mr *MockAvatarGetterMockRecorder) GetUserImage(ctx, userID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserImage", reflect.TypeOf((*MockAvatarGetter)(nil).GetUserImage), ctx, userID, size)
}
