// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aifedorov/goavatar/internal/handlers (interfaces: AvatarDeleter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_avatar_deleter.go -package=mocks . AvatarDeleter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarDeleter is a mock of AvatarDeleter interface.
type MockAvatarDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarDeleterMockRecorder
	isgomock struct{}
}

// MockAvatarDeleterMockRecorder is the mock recorder for MockAvatarDeleter.
type MockAvatarDeleterMockRecorder struct {
	mock *MockAvatarDeleter
}

// NewMockAvatarDeleter creates a new mock instance.
func NewMockAvatarDeleter(ctrl *gomock.Controller) *MockAvatarDeleter {
	mock := &MockAvatarDeleter{ctrl: ctrl}
	mock.recorder = &MockAvatarDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarDeleter) EXPECT() *MockAvatarDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAvatarDeleter) Delete(ctx context.Context, id uuid.UUID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarDeleterMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarDeleter)(nil).Delete), ctx, id, userID)
}
