// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aifedorov/goavatar/internal/handlers (interfaces: AvatarUploader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_avatar_uploader.go -package=mocks . AvatarUploader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/aifedorov/goavatar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarUploader is a mock of AvatarUploader interface.
type MockAvatarUploader struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUploaderMockRecorder
	isgomock struct{}
}

// MockAvatarUploaderMockRecorder is the mock recorder for MockAvatarUploader.
type MockAvatarUploaderMockRecorder struct {
	mock *MockAvatarUploader
}

// NewMockAvatarUploader creates a new mock instance.
func NewMockAvatarUploader(ctrl *gomock.Controller) *MockAvatarUploader {
	mock := &MockAvatarUploader{ctrl: ctrl}
	mock.recorder = &MockAvatarUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUploader) EXPECT() *MockAvatarUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockAvatarUploader) Upload(ctx context.Context, userID, fileName, mimeType string, sizeBytes int64, file io.Reader) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, userID, fileName, mimeType, sizeBytes, file)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarUploaderMockRecorder) Upload(ctx, userID, fileName, mimeType, sizeBytes, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarUploader)(nil).Upload), ctx, userID, fileName, mimeType, sizeBytes, file)
}
