// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aifedorov/goavatar/internal/handlers (interfaces: AvatarLister)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_avatar_lister.go -package=mocks . AvatarLister
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/aifedorov/goavatar/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarLister is a mock of AvatarLister interface.
type MockAvatarLister struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarListerMockRecorder
	isgomock struct{}
}

// MockAvatarListerMockRecorder is the mock recorder for MockAvatarLister.
type MockAvatarListerMockRecorder struct {
	mock *MockAvatarLister
}

// NewMockAvatarLister creates a new mock instance.
func NewMockAvatarLister(ctrl *gomock.Controller) *MockAvatarLister {
	mock := &MockAvatarLister{ctrl: ctrl}
	mock.recorder = &MockAvatarListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarLister) EXPECT() *MockAvatarListerMockRecorder {
	return m.recorder
}

// ListByUserID mocks base method.
func (m *MockAvatarLister) ListByUserID(ctx context.Context, userID string) ([]*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAvatarListerMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAvatarLister)(nil).ListByUserID), ctx, userID)
}
